name: drupal-demo
recipe: drupal9
config:
  webroot: web
  php: '8.0'
  composer_version: 2.0.7
  via: 'apache:2.4'
  database: 'mariadb:10.4'
  drush: ^11
  xdebug: false
tooling:
  drush:
    service: appserver
  installdrupal:
    service: appserver
    cmd: drush si minimal --site-name=drupal-demo --account-mail=karlitoskillyou@hotmail.com --account-name=root --account-pass=toor -y
  override:
    cmd:
      - appserver: composer install
      - appserver: drush si minimal --site-name=drupal-demo --account-mail=karlitoskillyou@hotmail.com --account-name=root --account-pass=toor --existing-config -y
      - appserver: drush cim -y
      - appserver: drush migrate:import --group=sample_terms
      - appserver: drush pokeapi:request
